services:
    guzzle.client:
        class: GuzzleHttp\Client

    # -------  clients

    app.client.bitstamp:
        class: AppBundle\Service\Client\BitstampClient
        arguments:
            - '@guzzle.client'
            - '%client.bitstamp%'

    app.client.itbit:
        class: AppBundle\Service\Client\ItbitClient
        arguments:
            - '@guzzle.client'
            - '%client.itbit%'

    app.client.kraken:
        class: AppBundle\Service\Client\KrakenClient
        arguments:
            - '@guzzle.client'
            - '%client.kraken%'

    app.client.okcoin:
        class: AppBundle\Service\Client\OkcoinClient
        arguments:
            - '@guzzle.client'
            - '%client.okcoin%'

    app.client.binance:
        class: AppBundle\Service\Client\BinanceClient
        arguments:
            - '@guzzle.client'
            - '%client.binance%'

    app.client.cexio:
        class: AppBundle\Service\Client\CexioClient
        arguments:
            - '@guzzle.client'
            - '%client.cexio%'

    app.client.bittrex:
        class: AppBundle\Service\Client\BittrexClient
        arguments:
            - '@guzzle.client'
            - '%client.bittrex%'

    app.client.quadrigacx:
        class: AppBundle\Service\Client\QuadrigacxClient
        arguments:
            - '@guzzle.client'
            - '%client.quadrigacx%'

    # -------  services

    app.bitstamp.service:
        class: AppBundle\Service\BitstampService
        arguments:
            - '@app.client.bitstamp'

    app.itbit.service:
        class: AppBundle\Service\ItbitService
        arguments:
            - '@app.client.itbit'

    app.kraken.service:
        class: AppBundle\Service\KrakenService
        arguments:
            - '@app.client.kraken'

    app.okcoin.service:
        class: AppBundle\Service\OkcoinService
        arguments:
            - '@app.client.okcoin'

    app.binance.service:
        class: AppBundle\Service\BinanceService
        arguments:
            - '@app.client.binance'

    app.cexio.service:
        class: AppBundle\Service\CexioService
        arguments:
            - '@app.client.cexio'

    app.bittrex.service:
        class: AppBundle\Service\BittrexService
        arguments:
            - '@app.client.bittrex'

    app.quadrigacx.service:
        class: AppBundle\Service\QuadrigacxService
        arguments:
            - '@app.client.quadrigacx'

    app.ticker.service:
        class: AppBundle\Service\TickerService
        arguments:
            - { bitstamp: '@app.bitstamp.service', itbit: '@app.itbit.service',  kraken: '@app.kraken.service', okcoin: '@app.okcoin.service', binance: '@app.binance.service', cexio: '@app.cexio.service', bittrex: '@app.bittrex.service', quadrigacx: '@app.quadrigacx.service'}

    app.balance.service:
        class: AppBundle\Service\BalanceService
        arguments:
            - { bitstamp: '@app.bitstamp.service', itbit: '@app.itbit.service',  kraken: '@app.kraken.service', okcoin: '@app.okcoin.service', binance: '@app.binance.service', cexio: '@app.cexio.service', bittrex: '@app.bittrex.service', quadrigacx: '@app.quadrigacx.service'}
            - '@app.balance.repository'

    app.difference.service:
        class: AppBundle\Service\DifferenceService
        arguments:
            - '@app.status.repository'
            - '@app.difference.repository'

    app.trade.service:
        class: AppBundle\Service\TradeService
        arguments:
             - { bitstamp: '@app.bitstamp.service', itbit: '@app.itbit.service',  kraken: '@app.kraken.service', okcoin: '@app.okcoin.service', binance: '@app.binance.service', cexio: '@app.cexio.service', bittrex: '@app.bittrex.service', quadrigacx: '@app.quadrigacx.service'}
             - '@app.order_pair.repository'
    # -------  repositories

    app.ticker.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Ticker

    app.balance.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Balance

    app.difference.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Difference

    app.status.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Status

    app.order_pair.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\OrderPair