AppBundle\Entity\OrderPair:
    type: entity
    repositoryClass: AppBundle\Repository\OrderPairRepository
    table: order_pair
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        buyOrderId:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: false
            precision: 0
        sellOrderId:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: true
            precision: 0
        buyOrderExchange:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: false
            precision: 0
        sellOrderExchange:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: true
            precision: 0
        sellOrderOpen:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            options: { "default": false }
            precision: 0
        buyOrderOpen:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            options: { "default": false }
            precision: 0
        buyOrderAmountBtc:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: false
            precision: 7
            options:
                default: 0
        sellOrderAmountBtc:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: true
            precision: 7
            options:
                default: 0
        buyOrderAmountUsd:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: false
            precision: 7
            options:
                default: 0
        sellOrderAmountUsd:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: true
            precision: 7
            options:
                default: 0
        buyOrderPrice:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: false
            precision: 7
            options:
                default: 0
        sellOrderPrice:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: true
            precision: 7
            options:
                default: 0
        buyOrderCreated:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        sellOrderCreated:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }