AppBundle\Entity\Ticker:
    type: entity
    repositoryClass: AppBundle\Repository\TickerRepository
    table: ticker
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: true
            precision: 0
        ask:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: true
            precision: 7
            options:
                default: 0
        bid:
            type: float
            scale: 2
            length: null
            unique: false
            nullable: true
            precision: 7
            options:
                default: 0
        created:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }